"""
Django settings for django_bug_manage project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ihs&b8e%sx^dl2t%qmljb4o%w-iwq9a3#=$d%7ax+=l)dqit!t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01.apps.App01Config',
    'web.apps.WebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'web.middleware.auth.AuthMiddleware',
]

ROOT_URLCONF = 'django_bug_manage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'app01/templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_bug_manage.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'  # 中文

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# 影响自动生成数据库时间字段；
#       USE_TZ = True，创建UTC时间写入到数据库。
#       USE_TZ = False，根据TIME_ZONE设置的时区进行创建时间并写入数据库
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# 这个Django项目中用到的静态文件都保存在哪些目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "web/static"),
]

# 腾讯短信
TENCENT_SMS_APP_ID = 666666
TENCENT_SMS_APP_KEY = "666666"

# 短信签名
TENCENT_SMS_SIGN = "666666"

# 短信模板
TENCENT_SMS_TEMPLATE = {
    'register': 577066,
    'login': 577065,
    'reset': 577064,
}

TENCENT_COS_ID = "COS的secret_id"
TENCENT_COS_KEY = "COS的secret_key"

# ------- 登录白名单: 无需登录就可以访问的页面 -------
WHITE_REGEX_URL_LIST = [
    "/web/register/",
    "/web/send/sms/",
    "/web/login/",
    "/web/login/sms/",
    "/web/image/code/",
    "/web/index/",
    "/web/price/",
]

try:
    from .local_settings import *
except ImportError:
    pass


# # 腾讯短信
# TENCENT_SMS_APP_ID = 1400351175
# TENCENT_SMS_APP_KEY = "b7c4c12598a3ae95dc7bfcd08adfd1e4"
#
# # 短信签名
# TENCENT_SMS_SIGN = "Bug管理系统"
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',  # 连接数据库的类型
#         'NAME': 'django_bug_manage',  # 数据库名
#         'HOST': '127.0.0.1',  # 数据库主机
#         'PORT': 3306,  # 数据库的端口
#         'USER': 'root',
#         'PASSWORD': 'root',
#     }
# }
#
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379",  # 安装redis的主机的 IP 和 端口
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             "CONNECTION_POOL_KWARGS": {
#                 "max_connections": 1000,
#                 "encoding": 'utf-8'
#             },
#             "PASSWORD": "djf19950815@."  # redis密码
#         }
#     }
# }
